package com.restaurant.model;

import java.util.UUID;

/**
 * Size of each instance = 16(object overhead) + 4(padding) + 8 +4 + 128 = 160byes
 */
public class CustomerGroup {
    //2*36+64 = 128
    private final String id;
    //4
    private final int size;
    //8
    private Table table;

    public CustomerGroup(int size) {
        this.size = size;
        id=UUID.randomUUID().toString();
    }

    public int getSize() {
        return size;
    }

    public Table getTable() {
        return table;
    }

    public void setTable(Table table) {
        this.table = table;
    }

    public String getId() {
        return id;
    }

    //Autogenerated equals and hashcode by the IDE.


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        CustomerGroup that = (CustomerGroup) o;

        if (size != that.size) return false;
        if (id != null ? !id.equals(that.id) : that.id != null) return false;
        return table != null ? table.equals(that.table) : that.table == null;

    }

    @Override
    public int hashCode() {
        int result = id != null ? id.hashCode() : 0;
        result = 31 * result + size;
        result = 31 * result + (table != null ? table.hashCode() : 0);
        return result;
    }

    @Override
    public String toString() {
        return "CustomerGroup{" +
                "id='" + id + '\'' +
                ", size=" + size +
                ", table=" + table +
                '}';
    }
}
